points:
  zones:
    matrix:
      anchor:
        rotate: 0
      columns:
        outer:
            key.stagger : 0
            key.column_net : P006
        pinky:
          key.stagger : 0
          key.column_net : P017
        ring:
          key.stagger:  10
          key.column_net : P020
        middle:
          key.stagger: 5
          key.column_net : P022
        index:
          key.stagger: -5
          key.column_net : P024
        inner:
          key.stagger: -4
          key.column_net : P100
        makros:
          key.stagger: -4
          key.column_net : P104
      rows:
        
        bottom:
          key.row_net : P031
        home:
          key.row_net : P029
        top:
          key.row_net : P002
        number:
          key.row_net : P115
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7-1u, -40]
      columns:
        near:
          key.column_net : P024
        home:
          key.spread: 1.1u
          key.splay: -7
          key.height : 1.75u
          key.stagger : -0.5u
          key.origin: [-11.75, -9]
          rows.thumb.skip : true
          key.column_net : P100
          
        far:
          key.spread: 21.25
          key.splay: -10
          key.stagger : 10
          key.column_net : P104

          key.origin: [-9.5, -9]
      rows:
        thumb:
          key.row_net : P113
        thumb2:
          key.row_net : P111
  rotate: 0
outlines:
  left:
    - where: true
      what: rectangle
      size: [cx + 3, cy + 3]
      fillet : 2

pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      keyswitches:
        what: mx
        where: /^matrix_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nicenano:
        what: nicenano
        params:
          orientation: "up"
        where:
          ref:  matrix_makros_top
          shift: [0,0]
          rotate: 0


